import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import Footer from "./_components/footer/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import NextAuthProvider from "./provider/next-auth.provider";
import 'sweetalert2/src/sweetalert2.scss'
import AuthFormContextProvider from "./context/AuthForm";
import CartContextProvider from "./context/CartContext";
import Script from 'next/script';


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={`antialiased`}
      >
        <NextAuthProvider>
          <AuthFormContextProvider>
            <CartContextProvider>
              <Navbar /> 
              <div className="">
                {children}
              </div>
              <Footer />
            </CartContextProvider>
          </AuthFormContextProvider>
        </NextAuthProvider>

        {/* <script src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js" defer></script> */}
        <Script
          src="https://cdn.jsdelivr.net/npm/flowbite@3.1.2/dist/flowbite.min.js"
          strategy="lazyOnload"
        />
      </body>
    </html>
  );
}
