import type { Metadata } from "next";
import "./globals.css";
import Navbar from "./_components/navbar/Navbar";
import Footer from "./_components/footer/Footer";
import "slick-carousel/slick/slick.css";
import "slick-carousel/slick/slick-theme.css";
import LoginContextProvider from "./context/LoginContext";
import NextAuthProvider from "./provider/next-auth.provider";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body suppressHydrationWarning={true}
        className={`antialiased`}
      >
        <NextAuthProvider>
          <LoginContextProvider>
            <Navbar />
            <div className="">
              {children}
            </div>
            <Footer />
          </LoginContextProvider>
        </NextAuthProvider>
      </body>
    </html>
  );
}
